# Include shared CI
include:
    - project: "epi2melabs/ci-templates"
      file: "wf-containers.yaml"

variables:
    # We'll use the single-file case for these runs
    NF_WORKFLOW_OPTS: "-executor.\\$$local.memory 16GB --fastq test_data/fastq --ref_host test_data/cell_line.fasta.gz --ref_helper test_data/helper.fasta --ref_rep_cap test_data/repcap.fasta  --itr1_start 11 --itr1_end 156 --itr2_start 2156 --itr2_end 2286 --ref_transgene_plasmid test_data/transgene.fasta --threads 4 "
    CI_FLAVOUR: "new" # set to "classic" for old-style CI

# Remove this block in downstream templates
singularity-run:
    tags: [] # no need for big ram
# end


docker-run:

    # Remove this directive in downstream templates
    tags:
      - large_ram

    # Define a 1D job matrix to inject a variable named MATRIX_NAME into
    #   the CI environment, we can use the value of MATRIX_NAME to determine
    #   which options to apply as part of the rules block below
    # NOTE There is a slightly cleaner way to define this matrix to include
    #   the variables, but it is broken when using long strings! See CW-756
    parallel:
        matrix:
            - MATRIX_NAME: [
                "fastq_input", "ubam_input", "fastq_input_splitbam"
                ]
    rules:
        # NOTE As we're overriding the rules block for the included docker-run
        #   we must redefine this CI_COMMIT_BRANCH rule to prevent docker-run
        #   being incorrectly scheduled for "detached merge request pipelines" etc.
        - if: ($CI_COMMIT_BRANCH == null || $CI_COMMIT_BRANCH == "dev-template")
          when: never
        - if: $MATRIX_NAME == "fastq_input"
          variables:
              NF_WORKFLOW_OPTS: "-executor.\\$$local.memory 16GB --fastq test_data/fastq --ref_host test_data/cell_line.fasta.gz --ref_helper test_data/helper.fasta --ref_rep_cap test_data/repcap.fasta --itr1_start 11 --itr1_end 156 --itr2_start 2156 --itr2_end 2286  --ref_transgene_plasmid test_data/transgene.fasta --threads 4"
              NF_IGNORE_PROCESSES: "split_bams_by_structure"
        - if: $MATRIX_NAME == "ubam_input"
          variables:
            NF_WORKFLOW_OPTS: "-executor.\\$$local.memory 16GB --bam test_data/ubam --ref_host test_data/cell_line.fasta.gz --ref_helper test_data/helper.fasta --ref_rep_cap test_data/repcap.fasta --itr1_start 11 --itr1_end 156 --itr2_start 2156 --itr2_end 2286  --ref_transgene_plasmid test_data/transgene.fasta --threads 4"
            NF_IGNORE_PROCESSES: "split_bams_by_structure"
        - if: $MATRIX_NAME == "fastq_input_splitbam"
          variables:
            NF_WORKFLOW_OPTS: "-executor.\\$$local.memory 16GB --fastq test_data/fastq --ref_host test_data/cell_line.fasta.gz --ref_helper test_data/helper.fasta --ref_rep_cap test_data/repcap.fasta --itr1_start 11 --itr1_end 156 --itr2_start 2156 --itr2_end 2286  --ref_transgene_plasmid test_data/transgene.fasta --output_genometype_bams --threads 4"